### ISSUE TITLE
Missing $event.

### ISSUE THREAD

**Issue by kfarkasHU** [portarto/oe-aspnet-mvc-chat-app#1]
https://github.com/portarto/oe-aspnet-mvc-chat-app/blob/9e7a1ee5a7585f27a1ba351fecb9bab06adaa906/src/WebApp/chat-ui/src/app/shared/base-components/base-modal/base-modal.component.html#L14

Please add `$event` paramter here.

**Comment by portarto** [comment]
Thank you for your valuable comments @kfarkasHU
